name: Deploy DB

on:
  push:
    branches:
      - main
    paths:
      - 'PostgresDemo.DbMigrator/**'
      - '.github/workflows/db-migrator.yml'
      - 'PostgresDemo.sln'
  workflow_dispatch:

jobs:
  deploy-db-migrator:
    runs-on: self-hosted
    environment: production

    steps:
      - uses: actions/checkout@v4

      - name: Clean previous publish output
        run: rm -rf publish

      - name: Restore DbMigrator
        run: dotnet restore PostgresDemo.DbMigrator/PostgresDemo.DbMigrator.csproj

      - name: Publish DbMigrator
        run: dotnet publish PostgresDemo.DbMigrator/PostgresDemo.DbMigrator.csproj -c Release -o publish/db-migrator

      - name: Run DB migrations
        run: dotnet publish/db-migrator/PostgresDemo.DbMigrator.dll
        env:
          DB_CONNECTION: ${{ secrets.DB_CONNECTION_STRING }}